service: ui-bot # NOTE: update this with your service name

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  memorySize: 2048
  timeout: 120
  architecture: arm64
  deploymentBucket:
    serverSideEncryption: AES256
  environment:
    OPENAI_API_KEY: ${ssm:openaiApiKey}
  ecr:
    images:
      uibot:
        path: src/
        buildArgs:
          DATA_PATH: ui/
      anchorbot:
        path: src/
        buildArgs:
          DATA_PATH: anchor/
      tdibot:
        path: src/
        buildArgs:
          DATA_PATH: tdi/
functions:
  ui:
    environment:
      PROGRAM_NAME: Unemployment Insurance in New Jersey
    image:
      name: uibot
    url:
      cors: true
  anchor:
    environment:
      PROGRAM_NAME: ANCHOR program in New Jersey
    image:
      name: anchorbot
    url:
      cors: true
  tdi:
    environment:
      PROGRAM_NAME: Temporary Disability and Family Leave Insurance
    image:
      name: tdibot
    url:
      cors: true
